FROM node:16-bullseye
ENV NODE_ENV=development
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production
COPY . .
EXPOSE 3010
RUN chown -R node /usr/src/app
USER node
CMD ["node", "dist/index.js"]
